apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core
  namespace: bitwarden
  labels:
    app: core
    type: persistentvolumeclaim
spec:
  storageClassName: bitwarden
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi