apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: sonarqube
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sonarqube
  resources:
    requests:
      storage: 31Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extensions
  namespace: sonarqube
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: sonarqube
  resources:
    requests:
      storage: 31Gi