apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: redmine
  labels:
    app: postgres
    type: persistentvolumeclaim
spec:
  storageClassName: redmine
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi