apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: redmine
  labels:
    app: redmine
    type: persistentvolumeclaim
spec:
  storageClassName: redmine
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: themes
  namespace: redmine
  labels:
    app: redmine
    type: persistentvolumeclaim
spec:
  storageClassName: redmine
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi