apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: owncloud
  namespace: owncloud
  labels:
    app: owncloud
    type: secret
stringData:
  OWNCLOUD_ADMIN_PASSWORD: password
  #OWNCLOUD_LICENSE_KEY: YOUR_BASE64_ENCODED_OWNCLOUD_LICENSE_KEY.
