apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
    type: statefulset
spec:
  serviceName: "keycloak"
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      type: pod 
  template:
    metadata:
      labels:
        app: keycloak
        type: pod
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_VENDOR
          valueFrom:
            configMapKeyRef:
              name: keycloak
              key: DB_VENDOR
        - name: DB_ADDR
          valueFrom:
            configMapKeyRef:
              name: keycloak
              key: DB_ADDR
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres
              key: POSTGRES_DB
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: postgres
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        - name: DB_SCHEMA
          valueFrom:
            configMapKeyRef:
              name: keycloak
              key: DB_SCHEMA
        - name: KEYCLOAK_USER
          valueFrom:
            configMapKeyRef:
              name: keycloak
              key: KEYCLOAK_USER
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak
              key: KEYCLOAK_PASSWORD
        - name: PROXY_ADDRESS_FORWARDING
          valueFrom:
            configMapKeyRef:
              name: keycloak
              key: PROXY_ADDRESS_FORWARDING
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080