apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: jenkins
  labels:
    app: jenkins
    type: persistentvolumeclaim
spec:
  storageClassName: jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi