apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bitwarden
  namespace: bitwarden
  labels:
    app: bitwarden
    type: secret
stringData:
  SERVER_ADMIN_EMAIL: admin@domain.tld
  SMTP_PASSWORD: password 
