apiVersion: v1
kind: ConfigMap
metadata:
  name: bitwarden
  namespace: bitwarden
  labels:
    app: bitwarden
    type: configmap
data:
  DOMAIN: "https://bitwarden.domain.tld"
  SIGNUPS_ALLOWED: "true"
  INVITATIONS_ALLOWED: "true"
  SHOW_PASSWORD_HINT: "true"
  WEB_VAULT_ENABLED: "true"
  SMTP_HOST: "mail.domain.tld"
  SMTP_FROM: "bitwarden@domain.tld"
  SMTP_PORT: "587"
  SMTP_SSL: "true"
  SMTP_USERNAME: "bitwarden@domain.tld"
