apiVersion: v1
kind: ConfigMap
metadata:
  name: jira
  namespace: jira
  labels:
    app: jira
    type: configmap
data:
  ATL_DB_TYPE: "postgres72"
  ATL_DB_DRIVER: "org.postgresql.Driver"
  ATL_DB_SCHEMA_NAME: "public"
  ATL_JDBC_URL: "jdbc:postgresql://postgres:5432/jira"
  JVM_MINIMUM_MEMORY: "2048m"
  JVM_MAXIMUM_MEMORY: "4096m"
  ATL_PROXY_PORT: "443"
  ATL_TOMCAT_PORT: "8080"
  ATL_TOMCAT_SCHEME: "https"
  ATL_TOMCAT_SECURE: "true"
      