apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: jira
  labels:
    app: jira
    type: persistentvolumeclaim
spec:
  storageClassName: jira
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi