apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: artifactory
  labels:
    app: artifactory
    type: persistentvolumeclaim
spec:
  storageClassName: artifactory
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi