apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db
  namespace: mattermost
  labels:
    app: postgres
    type: persistentvolumeclaim
spec:
  storageClassName: mattermost
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi