apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: mattermost
  labels:
    app: mattermost
    type: persistentvolumeclaim
spec:
  storageClassName: mattermost
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs
  namespace: mattermost
  labels:
    app: mattermost
    type: persistentvolumeclaim
spec:
  storageClassName: mattermost
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: mattermost
  labels:
    app: mattermost
    type: persistentvolumeclaim
spec:
  storageClassName: mattermost
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugins
  namespace: mattermost
  labels:
    app: mattermost
    type: persistentvolumeclaim
spec:
  storageClassName: mattermost
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi