apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: minio
  labels:
    app: minio
    type: persistentvolumeclaim
spec:
  storageClassName: minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi